on:
  pull_request:
    branches:
      - release-please--branches--main--components--svelte

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: peter-evans/merge-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
